provide development builds as artifacts
TBD54566975/ssi-service pull request #111
Opened 2022-09-24 12:53 UTC by pdxjohnny

Via upload of built binaries post validation

2022-09-24 13:56 UTC, pdxjohnny commented
I'm not really sure where the binaries get built too, I was planning on using the first CI run to verify if that's the right path

2022-09-24 14:31 UTC, pdxjohnny commented
Okay pretty sure this should do it

2022-09-27 15:26 UTC, decentralgabe requested changes
thanks @pdxjohnny can you add the upload artifacts to a new step separate from build, and put it under a mage command like `mage artifact` or similar?

also curious what the use is for having an artifact produced here?

2022-10-06 04:14 UTC, michaelneale commented
I guess the benefit is you have a versioned binary you can download vis the github CDN etc?

2022-10-07 05:38 UTC, michaelneale commented
but then they would have to run github actions locally etc. if its publishing binaries, ideally only want that done from trusted source (the github action server side).

2022-10-07 13:43 UTC, pdxjohnny commented on magefile.go
> +	fmt.Println("Building package...")
```suggestion
	fmt.Println("Building library...")
```

2022-10-07 13:54 UTC, pdxjohnny commented
Thanks for the comments! @michaelneale was spot on, as development here evolves I'd love to be able to pull from the latest stuff ASAP, without the need to replicate the build infrastructure (since I'm hoping to use this in many projects).

2022-10-07 16:18 UTC, decentralgabe approved these changes

2022-10-07 16:19 UTC, decentralgabe commented
yes, was referring to what you've included - building the artifact, not publishing it

2022-10-07 16:26 UTC, merged