show an example of gin middle ware for authorization and authentication
TBD54566975/ssi-service pull request #551
Opened 2023-06-21 09:17 UTC by michaelneale

# Overview
Implementers of an ssi-service may want to weave in authentication and authorization.

# Description
This shows how it can be done with stubbed out code which can be modified as needed. 
There isn't an easy runtime plugin mechanism for golang so this would likely be done by the implementer.

# How Has This Been Tested?

Regression tests covers this as it adds no functionality.

## References
https://github.com/gin-gonic/gin/blob/master/docs/doc.md#using-basicauth-middleware

2023-06-21 17:30 UTC, decentralgabe requested changes
I don't think we should add this to the main codeline, I'm fine with it living in an `examples` directory for extension.

I'm not certain we should add any auth, let alone user-based auth like this. If we do add auth I'd favor a DID-auth based solution. Until we have requirements, a design, and some consensus let's hold off on this.

2023-06-21 21:32 UTC, michaelneale commented
@decentralgabe yeah can be in examples/docs for sure. I think there needs to be flexibility for implementers. Is there did based auth already in there?

2023-06-21 23:20 UTC, decentralgabe commented
no DID auth yet, we have a ticket to track https://github.com/TBD54566975/ssi-sdk/issues/306

2023-06-22 06:32 UTC, decentralgabe approved these changes
Lgtm

2023-06-22 06:38 UTC, merged