OSE-25-sip-2-create-credential-manifest-crud-in-ssi-service
TBD54566975/ssi-service pull request #91
Opened 2022-09-08 23:38 UTC by nitro-neal

This is the implementation of the Credential Manifest CRUD functionality according to SIP 2
https://github.com/TBD54566975/ssi-service/tree/main/sip/sips/sip_2

<img width="765" alt="image" src="https://user-images.githubusercontent.com/5314059/189243460-9080ec2e-fc42-4ee2-92df-7ef68468c5fc.png">

**Postman Data**d
PUT Manifest

Input: 
```
{
  "@context": "",
  "issuer" : "did:example:123",
  "outputDescriptors": [
            {
                "id": "id1z1",
                "schema": "https://test.com/schema",
                "name": "good ID",
                "description": "it's all good"
            },
            {
                "id": "id2z",
                "schema": "https://test.com/schema",
                "name": "good ID",
                "description": "it's all good"
            }
        ],
   "presentationDefinition": {
    "id": "test",
    "input_descriptors": [
      {
        "id": "test input descriptor",
        "constraints" : 
            {
                "fields" : [ 
                    {
                    "path" : [
                        "path1"
                    ]
                    }
                ]
            }
        

      }
    ]
  }
}
```

Output
```
{
    "manifest": {
        "id": "a2170fed-81cd-42db-ad79-3d65ea720878",
        "issuer": {
            "id": "did:example:123",
            "name": "did:example:123"
        },
        "output_descriptors": [
            {
                "id": "id1z1",
                "schema": "https://test.com/schema",
                "name": "good ID",
                "description": "it's all good"
            },
            {
                "id": "id2z",
                "schema": "https://test.com/schema",
                "name": "good ID",
                "description": "it's all good"
            }
        ],
        "format": {
            "jwt": {
                "alg": [
                    "EdDSA"
                ]
            }
        },
        "presentation_definition": {
            "id": "test",
            "input_descriptors": [
                {
                    "id": "test input descriptor",
                    "constraints": {
                        "fields": [
                            {
                                "path": [
                                    "path1"
                                ]
                            }
                        ]
                    }
                }
            ]
        }
    }
}
```

2022-09-08 23:39 UTC, nitro-neal commented on go.mod
> +require github.com/oliveagle/jsonpath v0.0.0-20180606110733-2e52cf6e6852 // indirect
I don't see where I added this or used this? When I try to remove it brings it back when I mage build

2022-09-09 20:27 UTC, decentralgabe requested changes
one more thing - the `config.toml` files should be updated to have a new manifest entry

2022-09-09 20:27 UTC, decentralgabe commented on pkg/server/router/manifest.go
> +
where do you handle the query parameters?

2022-09-09 20:27 UTC, decentralgabe commented on pkg/server/router/manifest.go
> +func (cr ManifestRouter) GetManifest(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
nit: for schemas it's called `GetSchemaByID`, I think your name here is better, would you mind updating the schema to say `GetSchema` ?

2022-09-09 20:27 UTC, decentralgabe commented on pkg/service/manifest/storage/bolt.go
> +	gotmanifests, err := b.db.ReadAll(namespace)
gotManifests

2022-09-09 20:27 UTC, decentralgabe commented on pkg/service/manifest/storage/bolt.go
> +		var nextmanifest StoredManifest
nextManifest

2022-09-09 20:27 UTC, decentralgabe commented on pkg/service/manifest/model.go
> +	PresentationDefinition map[string]interface{}
these should use the object models from the sdk

2022-09-09 20:28 UTC, decentralgabe commented on pkg/service/manifest/storage/bolt.go
> +	//id := manifest.Schema.ID
remove

2022-09-09 23:06 UTC, decentralgabe approved these changes
Past the change to `config.toml`, lgtm!

2022-09-09 23:31 UTC, merged